/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.Controller_NienKhoa;
import controller.Controller_PhanCongHS;
import controller.Controller_QlDsLop;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Chitiethocsinh;
import models.HocSinh;

/**
 *
 * @author Duc
 */
public class QL_DaoTao_PhanCongHocSinh extends javax.swing.JFrame {

  private Controller_PhanCongHS connectedDB;
    private  DefaultTableModel tableModel;
        private  DefaultTableModel tableModel2;
     private static String maHS;
     private static String maLop;
     private List<HocSinh> listHS;
     private List<HocSinh> listHSLop;

    
    public QL_DaoTao_PhanCongHocSinh() {
        initComponents();
         this.setLocationRelativeTo(null);
         creatTableHSTT();
         creatTableHSLop();
        new Controller_NienKhoa().LayDanhSachNamHoc(ComboBoxNienKhoa);
        String namHoc = ComboBoxNienKhoa.getSelectedItem().toString();
        new Controller_QlDsLop().layDanhSachLopHoc(namHoc, ComboboxLopHoc);
        
        listHS = new Controller_PhanCongHS().listHSPC(namHoc);
        updateTableHSTT(listHS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxNienKhoa = new javax.swing.JComboBox<>();
        ComboboxLopHoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnPhanCong = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PHÂN CÔNG HỌC SINH");

        ComboBoxNienKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxNienKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxNienKhoaItemStateChanged(evt);
            }
        });

        ComboboxLopHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboboxLopHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboboxLopHocItemStateChanged(evt);
            }
        });

        jLabel2.setText("Năm Học");

        jLabel3.setText("Lớp Học");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnPhanCong.setText("Phân Công");
        btnPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanCongActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Danh sách học sinh toàn trường");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboboxLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxNienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnXoa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPhanCong)
                        .addGap(169, 169, 169))))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxNienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboboxLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxNienKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxNienKhoaItemStateChanged
         // TODO add your handling code here:
         if (ComboBoxNienKhoa.getSelectedItem() != null) {
            String namHoc = ComboBoxNienKhoa.getSelectedItem().toString();
           // connectedDB.layDanhSachLopHoc(namHoc, ComboboxLopHoc);
                    new Controller_QlDsLop().layDanhSachLopHoc(namHoc, ComboboxLopHoc);

        listHS = new Controller_PhanCongHS().listHSPC(ComboBoxNienKhoa.getSelectedItem().toString());
//        listHSLop = new Controller_PhanCongHS().listHSLH(ComboboxLopHoc.getSelectedItem().toString());
        updateTableHSTT(listHS);
//        updateTableHSLop(listHSLop);
        }
    }//GEN-LAST:event_ComboBoxNienKhoaItemStateChanged

    private void ComboboxLopHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboboxLopHocItemStateChanged
       
//        listHS = new Controller_PhanCongHS().listHSPC(ComboBoxNienKhoa.getSelectedItem().toString());
//        updateTableHSTT(listHS);
        listHSLop = new Controller_PhanCongHS().listHSLH(ComboboxLopHoc.getSelectedItem().toString(),ComboBoxNienKhoa.getSelectedItem().toString());
        updateTableHSLop(listHSLop);
    }//GEN-LAST:event_ComboboxLopHocItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         if (evt.getClickCount() == 1) { // Xử lý sự kiện khi nhấp chuột một lần
                    int selectedRow = jTable1.getSelectedRow();
                    if (selectedRow != -1) { // Kiểm tra nếu đã chọn một hàng
                         maHS = (String) jTable1.getValueAt(selectedRow, 0);
                        // Ở đây, giá trị "Mã giáo viên" của hàng đã được chọn là maGV
                       // System.out.println("Mã giáo viên của hàng đã chọn là: " + maGV);
                      // updateTableDsLop();
                    }
                }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnPhanCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanCongActionPerformed
       
        Chitiethocsinh ct = new Chitiethocsinh();
        ct.setMaHS(maHS);
        ct.setMaLop(new Controller_QlDsLop().layMaLopHoc(ComboboxLopHoc.getSelectedItem().toString(),ComboBoxNienKhoa.getSelectedItem().toString()));
        new Controller_PhanCongHS().addChiTietHocSinh(ct);
        listHS = new Controller_PhanCongHS().listHSPC(ComboBoxNienKhoa.getSelectedItem().toString());
        updateTableHSTT(listHS);
                listHSLop = new Controller_PhanCongHS().listHSLH(ComboboxLopHoc.getSelectedItem().toString(),ComboBoxNienKhoa.getSelectedItem().toString());

        updateTableHSLop(listHSLop);
    }//GEN-LAST:event_btnPhanCongActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (evt.getClickCount() == 1) { // Xử lý sự kiện khi nhấp chuột một lần
                    int selectedRow = jTable2.getSelectedRow();
                    if (selectedRow != -1) { // Kiểm tra nếu đã chọn một hàng
                        
                         maLop = new Controller_QlDsLop().layMaLopHoc(ComboboxLopHoc.getSelectedItem().toString(),ComboBoxNienKhoa.getSelectedItem().toString());
                         maHS = (String) jTable2.getValueAt(selectedRow, 0);
                         
                        // Ở đây, giá trị "Mã giáo viên" của hàng đã được chọn là maGV
                       // System.out.println("Mã giáo viên của hàng đã chọn là: " + maGV);
                       
                    }
                }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       Chitiethocsinh ct = new Chitiethocsinh();
       ct.setMaHS(maHS);
       ct.setMaLop(maLop);
       new Controller_PhanCongHS().deletephanCong(ct);
       listHS = new Controller_PhanCongHS().listHSPC(ComboBoxNienKhoa.getSelectedItem().toString());
        updateTableHSTT(listHS);
               listHSLop = new Controller_PhanCongHS().listHSLH(ComboboxLopHoc.getSelectedItem().toString(),ComboBoxNienKhoa.getSelectedItem().toString());

        updateTableHSLop(listHSLop);
    }//GEN-LAST:event_btnXoaActionPerformed
 private void creatTableHSTT(){
         tableModel = (DefaultTableModel) jTable1.getModel();        // viet them
         tableModel.setColumnIdentifiers(new Object[]{               // tao cac thuoc tinh ten cua cot trong bang
         "Mã Học Sinh ", "Tên Học Sinh " ,"Ngày Sinh"
        });
    }
 private void creatTableHSLop(){
         tableModel2 = (DefaultTableModel) jTable2.getModel();        // viet them
         tableModel2.setColumnIdentifiers(new Object[]{               // tao cac thuoc tinh ten cua cot trong bang
         "Mã Học Sinh ", "Tên Học Sinh " ,"Ngày Sinh"
        });
    }
 private void updateTableHSLop(List<HocSinh> listHS ){
       tableModel2.setRowCount(0); // Xóa dữ liệu trong bảng hiện tại
      
        for (HocSinh hs : listHS) {
            Object[] rowData = {
                hs.getMaHS(),
                hs.getHoTen(),
                hs.getNgaySinh(),
            };
            tableModel2.addRow(rowData);
        }
 }
    private void updateTableHSTT(List<HocSinh> listHS) {
        tableModel.setRowCount(0); // Xóa dữ liệu trong bảng hiện tại
      
        for (HocSinh hs : listHS) {
            Object[] rowData = {
                hs.getMaHS(),
                hs.getHoTen(),
                hs.getNgaySinh(),
            };
            tableModel.addRow(rowData);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_DaoTao_PhanCongHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_DaoTao_PhanCongHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_DaoTao_PhanCongHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_DaoTao_PhanCongHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_DaoTao_PhanCongHocSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxNienKhoa;
    private javax.swing.JComboBox<String> ComboboxLopHoc;
    private javax.swing.JButton btnPhanCong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
